### ISSUE TITLE
the problem of training data.

### ISSUE THREAD

**Issue by ckqsars** [Jack-CV/FaceKit#51]
@Jack-CV 我按照你文中所说 构造了基于widerface的旋转脸的数据，但是在训练模型的时候发现并不能达到你文中的效果，其中我只是修改了回归框的返回结果为左上角和右下角的坐标，但是训练的结果很不理想，我觉得可能是在生成训练数据上的差异。你可以把你生成训练旋转脸的代码分享一下 或者把生成的数据给一个链接？
谢谢~

**Comment by Jack-CV** [comment]
Hi, I am very busy recently, and will release training code later.
