### ISSUE TITLE
速度问题

### ISSUE THREAD

**Issue by yzhang610** [Jack-CV/FaceKit#57]
您好，先问一下，您论文中写的，CPU下速度能够达到29fps是如何测出来的，因为我这边用您的那些视频测试，调用detect函数的时间就400~1000+ms，所以想问一下29fps是如何测出来的，谢谢啦

**Comment by Jack-CV** [comment]
论文中的数据是用640*480的分辨率的视频测试出的，最小脸设置为45，在一台 3.4GHz CPU的电脑上
