### ISSUE TITLE
test result 1280X720 CPU 2.7Ghz MacBook

### ISSUE THREAD

**Issue by MyraBaba** [Jack-CV/FaceKit#58]
I succesfully compiled and testted on my mcabook pro 2017 2.7 GHZ

1280X720 . resolution 

1 face at the scene ~ 10fps
more than 1 face .  ~ 4fps

its using only one Core I have 8 cores. 

How can it be use all available core ? than we can say it could be a realtime in 8 core 2.7 Ghz ?

is it could be done through blas or we need to code multithread something.?

**Comment by Jack-CV** [comment]
@MyraBaba  I add a tracking network for PCN and the speed is very fast now.  You can try it.

**Comment by MyraBaba** [comment]
will try today, let you know the results.

Best

**Comment by Jack-CV** [comment]
@MyraBaba And I guess you can set a larger minFaceSize (70, e.g.), since you use 1280X720 video rather than 640X480.
