### ISSUE TITLE
How to filter out the hard negative samples via the trained PCN-1

### ISSUE THREAD

**Issue by runningJ** [Jack-CV/FaceKit#59]
Hi Jack-CV
I has trained the pcn-1 stage reference your papper. However, i have no idea about "filter out the hard negative samples via the trained PCN-1". Can you give me some helps. Thank you very much @Jack-CV

**Comment by Jack-CV** [comment]
Hi, I am very busy recently, and will release training code later.

**Comment by allenwangcheng** [comment]
i have the same problem

**Comment by EngrNadeemShah** [comment]
Same problem
