### ISSUE TITLE
Trainging phase: input size of PCN-1 is 12*12?

### ISSUE THREAD

**Issue by jasminezz** [Jack-CV/FaceKit#62]
PCN-1 is a full convolution network, the input size in prediction is any size.
When training the network, we should do Random sampling as mtcnn to get training data, do we need to resize this pic to 12*12 ?

**Comment by lumialengine** [comment]
PCN-1 is not a full convolution network and the input size is 24*24.

**Comment by jasminezz** [comment]
@lumialengine you should see the PCN-1 prototxt first, the network is a full convolution network

**Comment by lumialengine** [comment]
@jasminezz but the paper is
![screenshot from 2019-01-08 14-31-41](https://user-images.githubusercontent.com/24852202/50814239-f11e0300-1353-11e9-9b25-216b9af250b7.png)
the InnerProduct is mean fully connected?

**Comment by jasminezz** [comment]
@lumialengine the code shows , they using "Convolution layer" replace the "InnerProduct layer" in PCN-1, like this:
```
layer {
  name: "fc6_1"
  type: "Convolution"
  bottom: "fc4_1"
  top: "fc6_1"
  convolution_param {
    num_output: 2
    kernel_size: 1
  }
}
```

**Comment by jasminezz** [comment]
I have trained the model with inputsize 24*24 , and it proved effectively

**Comment by mrgloom** [comment]
According to this thread, yes, it's fully convolutional.
https://github.com/Jack-CV/FaceKit/issues/11
