### ISSUE TITLE
How to train three models by your PCN_1, PCN_2 and PCN_3?

### ISSUE THREAD

**Issue by wsqat** [Jack-CV/FaceKit#65]
Dear, Thank you your papre. Please tell me how to train models by your PCN_1, PCN_2 and PCN_3? Do I need to rewrite loss_layer ?

**Comment by Jack-CV** [comment]
Hi, I am very busy recently, and will release training code later.

**Comment by wsqat** [comment]
OK, that's cool,  thank you very much again !

**Comment by AshishKumar4** [comment]
Hey, This issue has been dormant for a while now. Can't find any training implementation on the internet. Is it possible for you to provide the training code rn? Or a reference to some other implementation? Thanks!

**Comment by quickgrid** [comment]
Hello, is there any update to the training code availability?

**Comment by EngrNadeemShah** [comment]
Has anyone implemented training or re-training (transfer learning) of this PCN model in pytorch, tensorflow?

**Comment by ArmstrongYang** [comment]
您好，已经收到邮件，我会尽快处理给予回复，谢谢！
