### ISSUE TITLE
what is the role of SetTrackingPeriod

### ISSUE THREAD

**Issue by ericQiang** [Jack-CV/FaceKit#67]
Hi Jack-CV:
what is the role of SetTracking Period？
when i mask the following code in the video.cpp
`detector.SetTrackingPeriod(30);
    detector.SetTrackingThresh(0.6);`
It will cannot detect face any more.
and, when i unmask the two line codes, it will be work.
I found that when i unmask them, the function Detect will consume many time ?
Is there a method reduce the time consume of Detect?

**Comment by ericQiang** [comment]
oh, it't my mistake, 
I remain use the function 'DetectTrack' when i mask the following code in the video.cpp
`detector.SetTrackingPeriod(30); 
detector.SetTrackingThresh(0.6);`
I should be use 'Detect'

and the same question:  Is there a method reduce the time consume of Detect?

**Comment by Jack-CV** [comment]
Yes, there are many methods, such setting smaller minFaceSize, retraining PCN with smaller networks, using a much faster CNN lib rather than caffe (as far as I know, many company has private CNN lib that can run much faster than caffe)

**Comment by ericQiang** [comment]
@Jack-CV 
Thanks for your patient reply.^_^
