### ISSUE TITLE
Impl::SmoothWindow seems have a bug?

### ISSUE THREAD

**Issue by mrgloom** [Jack-CV/FaceKit#75]
Looks like we never enter here:
https://github.com/Jack-CV/FaceKit/blob/bdaf4d07e8712828d97be4f0435d307a111e6a85/PCN/PCN.cpp#L565

preList not used
https://github.com/Jack-CV/FaceKit/blob/bdaf4d07e8712828d97be4f0435d307a111e6a85/PCN/PCN.cpp#L587

winList will be the same, i.e. function do nothing.

**Comment by Jack-CV** [comment]
@mrgloom Thanks for your interests. You could refer to https://www.geeksforgeeks.org/static-keyword-cpp/

**Comment by mrgloom** [comment]
Yes, I missed the `static` keyword, so `preList` will be inited at first pass.
